### ISSUE TITLE
Random "Invalid state" errors

### ISSUE THREAD

**Issue by zerowebcorp** [thephpleague/oauth2-google#124]
When integrated with Symfony 7.1 with knp university oauth library with this, I am often getting issues authenticating with google. Many users are complaining and this is completely random and I don't have a way to replicate the issue other than just trying a few times. Most notably on MacOs and sometimes on android mobile. 

The error log shows

```
{
  "message": "Authenticator failed.",
  "context": {
    "exception": {
      "class": "Symfony\Component\Security\Core\Exception\AuthenticationException",
      "message": "Authentication failed. Invalid state",
      "code": 0,
      "file": "/app/src/Security/GoogleAuthenticator.php:80"
    },
    "authenticator": "App\Security\GoogleAuthenticator"
  },
  "level": 200,
  "level_name": "INFO",
  "channel": "security",
  "datetime": "2024-06-17T04:28:57.207783+00:00",
  "extra": {
    "token": "2n40mtlq-11139967",
    "env": "prod"
  }
}

```

Can someone help identifying the issue?

app/src/Security/GoogleAuthenticator.php
```
<?php

namespace App\Security;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use KnpU\OAuth2ClientBundle\Security\Authenticator\OAuth2Authenticator;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\RememberMeBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Http\Authenticator\Passport\SelfValidatingPassport;
use Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface;

class GoogleAuthenticator extends OAuth2Authenticator implements AuthenticationEntryPointInterface
{
    private $clientRegistry;
    private $entityManager;
    private $router;

    public function __construct(ClientRegistry $clientRegistry, EntityManagerInterface $entityManager, RouterInterface $router)
    {
        $this->clientRegistry = $clientRegistry;
        $this->entityManager = $entityManager;
        $this->router = $router;
    }

    public function supports(Request $request): ?bool
    {
        return $request->attributes->get('_route') === 'connect_google_check';
    }

    public function authenticate(Request $request): Passport
    {
        $client = $this->clientRegistry->getClient('google');

        try {
            /** @var \League\OAuth2\Client\Provider\GoogleUser $authenticatedUser */
            $authenticatedUser = $client->fetchUser();
            $email = $authenticatedUser->getEmail();
            $ipAddress = $_SERVER['HTTP_CF_CONNECTING_IP'] ?? $request->getClientIp();

            return new SelfValidatingPassport(
                new UserBadge($email, function () use ($authenticatedUser, $ipAddress) {
                    $user = $this->entityManager->getRepository(User::class)->findOneBy(['email' => $authenticatedUser->getEmail()]);

                    if (!$user) {
                        $user = new User();
                        $user->setEmail($authenticatedUser->getEmail());
                        $user->setStatus(USER::STATUS_ACTIVE);
                        $user->setReferralId(uniqid());
                        $user->setRoles(["ROLE_USER"]);
                    }

                    $user->setFirstName($authenticatedUser->getFirstName());
                    $user->setLastName($authenticatedUser->getLastName());
                    $user->setProfilePicture($authenticatedUser->getAvatar());
                    $user->setLastLoginTime(new \DateTime());
                    $user->setLastLoginIPAddress($ipAddress);
                    $this->entityManager->persist($user);
                    $this->entityManager->flush();

                    if ($user->getStatus() == User::STATUS_SUSPENDED) {
                        throw new AuthenticationException('Authentication failed. The user is suspended');
                    }

                    return $user;
                })
                , [new RememberMeBadge()]);
        } catch (\Exception $e) {
            // Store the exception message in the session to be handled in onAuthenticationFailure
            $request->getSession()->set('auth_error', $e->getMessage());
            // Throw an AuthenticationException to trigger the failure handler
            throw new AuthenticationException('Authentication failed. ' . $e->getMessage());
        }
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        $targetUrl = $request->getSession()->get('target_path', $this->router->generate('customer_homepage'));
        $request->getSession()->remove('target_path');
        return new RedirectResponse($targetUrl);
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        // Retrieve the error message from the session
        $errorMessage = $request->getSession()->get('auth_error', 'Authentication failed.');
        // Optionally, log the error message or take other actions

        // Redirect to the login page with an error message
        $loginUrl = $this->router->generate('customer_welcome');
        $request->getSession()->getFlashBag()->add('error', $errorMessage);

        return new RedirectResponse($loginUrl);
    }

    public function start(Request $request, AuthenticationException $authException = null): Response
    {
        $request->getSession()->set('target_path', $request->getUri());
        return new RedirectResponse(
            $this->router->generate('customer_welcome'),
            Response::HTTP_TEMPORARY_REDIRECT
        );
    }
}

```

app/config/packages/knpu_oauth2_client.yaml
```
knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: 'client_id_goes_here'
            client_secret: 'client_secret_goes_here'
            redirect_route: connect_google_check
            redirect_params: { }
              # Optional value for sending access_type parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters
              # access_type: null
              # Optional value for sending hd parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#hd-param
              # hosted_domain: null
              # Optional value for additional fields to be requested from the user profile. If set, these values will be included with the defaults. More details: https://developers.google.com/+/web/api/rest/latest/people
              # user_fields: {}
              # Optional value if you don't want or need to enable Google+ API access.
              # use_oidc_mode: false
            # whether to check OAuth2 "state": defaults to true
            use_state: true
```
